### ISSUE TITLE
Could you give me a copy of the source code?

### ISSUE THREAD

**Issue by tianchiguaixia** [MvMukesh/Any-Financial-Document-Data-Extractor#1]
Could you give me a copy of the source code?

**Comment by MvMukesh** [comment]
Why you need it? Sorry for late reply?

**Comment by tianchiguaixia** [comment]
No need, I have already implemented it

https://github.com/MvMukesh/AutoKYC-ExtractionEngine/assets/29837553/b5949959-7156-438f-98cd-b16ec3eb8d35
